SELECT 
a.site,
b.run_date report_date,
a.crawl_datetime,
a.crawl_date,
domain,
domain_canonical,
url,
canonical_url_length,
longest_url_length,
url_stripped,
canonical_url,
canonical_url_stripped,
canonical_status,
url_protocol,
canonical_url_protocol,
protocol_match,
protocol_count,
path_count,
first_path,
last_path,
query_string,
filename,
last_subfolder,
last_subfolder_canonical,
first_subfolder,
second_subfolder,
urls_to_canonical,
found_at_sitemap,
http_status_code,
level,
schema_type,
header_content_type,
word_count, 
med_word_count,
replace(replace(page_title,'(',''),')','') page_title,
page_title_length,
replace(replace(description,'(',''),')','') description,
description_length,
indexable,
robots_noindex,
meta_noindex,
is_self_canonical,
backlink_count,
backlink_domain_count,
redirected_to_url,
found_at_url,
rel_next_url,
rel_prev_url,
links_in_count,
links_out_count,
external_links_count,
internal_links_count,
h1_tag,
h2_tag,
redirect_chain,
redirected_to_status_code,
is_redirect_loop,
duplicate_page,
duplicate_page_count,
duplicate_body,
duplicate_body_count,
class_sitemap,
class_schema,
flag_google_maps,
flag_blog_path,
flag_blog_h1,
flag_high_word_count,
flag_thin_page,
flag_reviews,
flag_select_size,
flag_add_to_cart,
flag_prices,
flag_above_avg_prices,
flag_form_submit,
flag_learn_more,
flag_info_path,
flag_paginated,
CASE WHEN http_status_code = 404 THEN '' 
	WHEN url = domain THEN 'homepage'
	WHEN url like '%404%' THEN '404'
	WHEN class_schema is not null THEN class_schema 
	WHEN class_sitemap is not null THEN class_sitemap
	WHEN flag_learn_more = 1 OR flag_paginated = 1 OR url like '%/category/%' THEN 'category'
	WHEN (flag_reviews + flag_select_size + flag_add_to_cart + flag_prices) >= 2 THEN 'product'
	WHEN flag_google_maps = 1 THEN 'local'
	WHEN flag_form_submit = 1 THEN 'lead generation'
	WHEN flag_thin_page = 1 THEN 'thin content'
	ELSE 'general content' END as page_type 
FROM 
(
	SELECT 
	site,
	crawl_datetime,
	crawl_date,
	crawl_month,
	crawl_report_month,
	domain,
	domain_canonical,
	url,
	canonical_url_length,
	first_value(canonical_url_length) over (partition by url_stripped order by canonical_url_length desc) longest_url_length,
	url_stripped,
	canonical_url,
	canonical_url_stripped,
	canonical_status,
	url_protocol,
	canonical_url_protocol,
	protocol_match,
	protocol_count,
	path_count,
	first_path,
	last_path,
	query_string,
	filename,
	last_subfolder,
	last_subfolder_canonical,
	first_subfolder,
	second_subfolder,
	urls_to_canonical,
	found_at_sitemap,
	http_status_code,
	level,
	schema_type,
	header_content_type,
	word_count, 
	med_word_count,
	page_title,
	page_title_length,
	description,
	description_length,
	indexable,
	robots_noindex,
	meta_noindex,
	is_self_canonical,
	backlink_count,
	backlink_domain_count,
	redirected_to_url,
	found_at_url,
	rel_next_url,
	rel_prev_url,
  	links_in_count,
  	links_out_count,
  	external_links_count,
  	internal_links_count,	
	h1_tag,
	h2_tag,
	redirect_chain,
	redirected_to_status_code,
	is_redirect_loop,
	duplicate_page,
	duplicate_page_count,
	duplicate_body,
	duplicate_body_count,
	class_sitemap,
	class_schema,
	flag_google_maps,
	flag_blog_path,
	flag_blog_h1,
	flag_high_word_count,
	flag_thin_page,
	flag_reviews,
	flag_select_size,
	flag_add_to_cart,
	flag_prices,
	flag_above_avg_prices,
	flag_learn_more,
	flag_info_path,
	flag_form_submit,
	flag_paginated
	-- (flag_reviews + flag_select_size + flag_add_to_cart + flag_prices) as product_score,
	-- (flag_reviews + flag_select_size + flag_add_to_cart + flag_above_avg_prices) as category_score,
	-- (flag_blog_path + flag_blog_h1 + flag_high_word_count) as article_score
	FROM {{ref('deepcrawl_url_proc')}}
) a
LEFT JOIN {{ ref('crawl_dates') }} b
ON (
	a.crawl_date = b.crawl_date AND
	a.site = b.site
)
where ( canonical_url_length = longest_url_length or longest_url_length is null )
