SELECT * 
FROM
(
  SELECT 
  a.domain,
  b.site,
  regexp_extract(canonical_url,r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)') as domain_canonical,
  lower(concat(trim(replace(replace(replace(url,'www.',''),'http://',''),'https://',''),'/'),'/')) as url,
  lower(concat(trim(regexp_replace(replace(replace(replace(url,'www.',''),'http://',''),'https://',''),r'\?.*$',''),'/'),'/')) as url_stripped,
  lower(concat(trim(replace(replace(replace(canonical_url,'www.',''),'http://',''),'https://',''),'/'),'/')) canonical_url,
  lower(concat(trim(regexp_replace(replace(replace(replace(canonical_url,'www.',''),'http://',''),'https://',''),r'\?.*$',''),'/'),'/')) canonical_url_stripped,
  count(url) OVER (PARTITION by canonical_url) urls_to_canonical,
  case when url like '%?%' then 1 else 0 end as url_query_string_flag,
  case when canonical_url like '%?%' and canonical_url is not null then 1 else 0 end as canonical_query_string_flag,
  crawl_datetime,
  crawl_date,
  crawl_month,
  date_sub(crawl_month, INTERVAL 1 MONTH) crawl_report_month,
  first_value(crawl_datetime) OVER (PARTITION BY a.domain, crawl_month, url ORDER BY crawl_datetime desc) latest_crawl_datetime,
  found_at_sitemap,
  http_status_code,
  case when url like 'https%' then 'https' 
    when url like 'http%' then 'http'
    else 'none' end as url_protocol,
  case when canonical_url like 'https%' then 'https' 
    when canonical_url like 'http%' then 'http'
    else 'none' end as canonical_url_protocol,  
  level,
  lower(schema_type) schema_type,
  header_content_type,
  word_count, 
  page_title,
  page_title_length,
  description,
  description_length,
  indexable,
  robots_noindex,
  is_self_canonical,
  backlink_count,
  backlink_domain_count,
  redirected_to_url,
  self_redirect,
  found_at_url,
  rel_next_url,
  rel_prev_url,
  links_in_count,
  links_out_count,
  external_links_count,
  internal_links_count,
  lower(h1_tag) h1_tag,
  lower(h2_tag) h2_tag,
  redirect_chain,
  redirected_to_status_code,
  is_redirect_loop,
  duplicate_page,
  duplicate_page_count,
  duplicate_body,
  duplicate_body_count,
  (LENGTH(decimal_price) - LENGTH(REGEXP_REPLACE(decimal_price, '"', '')))/2 as qt_dec_price,
  (LENGTH(currency_price) - LENGTH(REGEXP_REPLACE(currency_price, '"', '')))/2 as qt_cur_price,
  (LENGTH(Add_to_cart) - LENGTH(REGEXP_REPLACE(Add_to_cart, '"', '')))/2 as qt_add_to_cart,
  (LENGTH(Google_Maps) - LENGTH(REGEXP_REPLACE(Google_Maps, '"', '')))/2 as qt_google_maps,
  (LENGTH(Learn_more) - LENGTH(REGEXP_REPLACE(Learn_more, '"', '')))/2 as qt_learn_more,
  (LENGTH(Review) - LENGTH(REGEXP_REPLACE(Review, '"', '')))/2 as qt_reviews,
  (LENGTH(Size) - LENGTH(REGEXP_REPLACE(Size, '"', '')))/2 as qt_size,
  (LENGTH(form_submit) - LENGTH(REGEXP_REPLACE(form_submit, '"', '')))/2 as qt_form_submit,
  (LENGTH(infinite_scroll) - LENGTH(REGEXP_REPLACE(infinite_scroll, '"', '')))/2 as qt_infinite_scroll,
  decimal_price,
  currency_price,
  add_to_cart,
  learn_more,
  review,
  size
  FROM
  ( 
    -- SELECT 
    -- url,
    -- canonical_url,
    -- crawl_datetime,
    -- found_at_sitemap,
    -- http_status_code,
    -- level,
    -- schema_type,
    -- header_content_type,
    -- word_count, 
    -- page_title,
    -- page_title_length,
    -- description,
    -- description_length,
    -- indexable,
    -- robots_noindex,
    -- is_self_canonical,
    -- backlink_count,
    -- backlink_domain_count,
    -- redirected_to_url,
    -- found_at_url,
    -- rel_next_url,
    -- rel_prev_url,
    -- links_in_count,
    -- links_out_count,
    -- external_links_count,
    -- internal_links_count,
    -- h1_tag,
    -- h2_tag,
    -- redirect_chain,
    -- redirected_to_status_code,
    -- is_redirect_loop,
    -- duplicate_page,
    -- duplicate_page_count,
    -- duplicate_body,
    -- duplicate_body_count,
    -- decimal_price,
    -- currency_price,
    -- add_to_cart,
    -- google_maps,
    -- learn_more,
    -- review,
    -- size,
    -- form_submit,
    -- infinite_scroll,
    -- decimal_price,
    -- currency_price,
    -- add_to_cart,
    -- learn_more,
    -- review,
    -- size
    -- FROM  
    -- `{{ target.project }}.seo_audit.deepcrawl_cifl` 

    -- UNION ALL

      SELECT 
      url,
      regexp_extract(url,r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)') as domain,
      canonical_url,
      crawl_datetime,
      cast(crawl_datetime as date) crawl_date,
      DATE_TRUNC(date( crawl_datetime ), month) crawl_month,
      found_at_sitemap,
      http_status_code,
      level,
      schema_type,
      header_content_type,
      word_count, 
      page_title,
      page_title_length,
      description,
      description_length,
      indexable,
      robots_noindex,
      is_self_canonical,
      backlink_count,
      backlink_domain_count,
      redirected_to_url,
      CASE WHEN regexp_extract(trim(redirected_to_url, '/'),r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)') = regexp_extract(url ,r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)')
        OR regexp_extract(trim(url, '/'),r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)') = regexp_extract(redirected_to_url ,r'^(?:https?:\/\/)?(?:www\.)?([^\/]+)')
        THEN 1 ELSE 0 END as self_redirect,
      found_at_url,
      rel_next_url,
      rel_prev_url,
      links_in_count,
      links_out_count,
      external_links_count,
      internal_links_count,
      replace(replace(replace(h1_tag, "[\"",""),"\"]",""),'"','') h1_tag,
      replace(replace(replace(h2_tag, "[\"",""),"\"]",""),'"','') h2_tag,
      redirect_chain,
      redirected_to_status_code,
      is_redirect_loop,
      duplicate_page,
      duplicate_page_count,
      duplicate_body,
      duplicate_body_count,
      form_submit,
      infinite_scroll,
      decimal_price,
      currency_price,
      google_maps,
      add_to_cart,
      learn_more,
      review,
      size
      FROM  
      `{{ target.project }}.{{ target.schema }}.deepcrawl` 
      WHERE url not like '%target=_blank%'
      and ( url = primary_url OR primary_url is null )
    ) a
  LEFT JOIN {{ ref('domains_proc') }} b
  ON (
    a.domain = b.domain
    )
 )
WHERE latest_crawl_datetime = crawl_datetime
AND self_redirect = 0 
